[package]
name = "ray-tracing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = {version = "0.8.4"}

[lib]
doctest = false

[[bin]]
name = "ray-tracing"
test = false
bench = false